# Generated by Django 3.1 on 2021-02-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=200)),
                ('campus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_no', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
        migrations.CreateModel(
            name='permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=200)),
                ('permission_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_no', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.faculty')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.class_room')),
            ],
        ),
        migrations.CreateModel(
            name='credential',
            fields=[
                ('login_user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.permission')),
            ],
        ),
        migrations.CreateModel(
            name='course_enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.session')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department'),
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.faculty')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.session')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_no', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
    ]
