# Generated by Django 3.1 on 2021-03-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210305_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
