# Generated by Django 3.1 on 2021-03-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210309_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='marked_by',
            field=models.CharField(max_length=100),
        ),
    ]
